//
// Generated file, do not edit! Created by opp_msgc 4.5 from ExtendedMessage/ExtendedMessage.msg.
//

#ifndef _EXTENDEDMESSAGE_M_H_
#define _EXTENDEDMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ExtendedMessage/ExtendedMessage.msg</tt> by opp_msgc.
 * <pre>
 * message ExtendedMessage extends cMessage
 * {
 * 	int source;
 *     int destination;
 *     int hopCount = 0;    
 * }
 * </pre>
 */
class ExtendedMessage : public ::cMessage
{
  protected:
    int source_var;
    int destination_var;
    int hopCount_var;

  private:
    void copy(const ExtendedMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ExtendedMessage&);

  public:
    ExtendedMessage(const char *name=NULL, int kind=0);
    ExtendedMessage(const ExtendedMessage& other);
    virtual ~ExtendedMessage();
    ExtendedMessage& operator=(const ExtendedMessage& other);
    virtual ExtendedMessage *dup() const {return new ExtendedMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doPacking(cCommBuffer *b, ExtendedMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ExtendedMessage& obj) {obj.parsimUnpack(b);}


#endif // _EXTENDEDMESSAGE_M_H_
