//
// Generated file, do not edit! Created by nedtool 4.6 from Packets/NetworkPacket.msg.
//

#ifndef _NETWORKPACKET_M_H_
#define _NETWORKPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "SimpleAddress.h"
// }}

/**
 * Class generated from <tt>Packets/NetworkPacket.msg:33</tt> by nedtool.
 * <pre>
 * // Basic application packet definition
 * //
 * // subclass if you want to create your own application layer packet
 * // class
 * //
 * // @author Daniel Willkomm
 * packet NetworkPacket
 * {
 *     LAddress::L3Type destAddr = LAddress::L3BROADCAST; // destination address
 *     LAddress::L3Type srcAddr = LAddress::L3BROADCAST; // source address
 * }
 * </pre>
 */
class NetworkPacket : public ::cPacket
{
  protected:
    LAddress::L3Type destAddr_var;
    LAddress::L3Type srcAddr_var;

  private:
    void copy(const NetworkPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NetworkPacket&);

  public:
    NetworkPacket(const char *name=NULL, int kind=0);
    NetworkPacket(const NetworkPacket& other);
    virtual ~NetworkPacket();
    NetworkPacket& operator=(const NetworkPacket& other);
    virtual NetworkPacket *dup() const {return new NetworkPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual LAddress::L3Type& getDestAddr();
    virtual const LAddress::L3Type& getDestAddr() const {return const_cast<NetworkPacket*>(this)->getDestAddr();}
    virtual void setDestAddr(const LAddress::L3Type& destAddr);
    virtual LAddress::L3Type& getSrcAddr();
    virtual const LAddress::L3Type& getSrcAddr() const {return const_cast<NetworkPacket*>(this)->getSrcAddr();}
    virtual void setSrcAddr(const LAddress::L3Type& srcAddr);
};

inline void doPacking(cCommBuffer *b, NetworkPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NetworkPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _NETWORKPACKET_M_H_

