//
// Generated file, do not edit! Created by opp_msgc 4.5 from Packets/NetworkPacket.msg.
//

#ifndef _NETWORKPACKET_M_H_
#define _NETWORKPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "SimpleAddress.h"
// }}



/**
 * Class generated from <tt>Packets/NetworkPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet NetworkPacket
 * {
 *     LAddress::L3Type destAddr = LAddress::L3BROADCAST; 
 *     LAddress::L3Type srcAddr  = LAddress::L3BROADCAST; 
 * }
 * </pre>
 */
class NetworkPacket : public ::cPacket
{
  protected:
    LAddress::L3Type destAddr_var;
    LAddress::L3Type srcAddr_var;

  private:
    void copy(const NetworkPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NetworkPacket&);

  public:
    NetworkPacket(const char *name=NULL, int kind=0);
    NetworkPacket(const NetworkPacket& other);
    virtual ~NetworkPacket();
    NetworkPacket& operator=(const NetworkPacket& other);
    virtual NetworkPacket *dup() const {return new NetworkPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual LAddress::L3Type& getDestAddr();
    virtual const LAddress::L3Type& getDestAddr() const {return const_cast<NetworkPacket*>(this)->getDestAddr();}
    virtual void setDestAddr(const LAddress::L3Type& destAddr);
    virtual LAddress::L3Type& getSrcAddr();
    virtual const LAddress::L3Type& getSrcAddr() const {return const_cast<NetworkPacket*>(this)->getSrcAddr();}
    virtual void setSrcAddr(const LAddress::L3Type& srcAddr);
};

inline void doPacking(cCommBuffer *b, NetworkPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NetworkPacket& obj) {obj.parsimUnpack(b);}


#endif // _NETWORKPACKET_M_H_
