//
// Generated file, do not edit! Created by opp_msgc 4.5 from BatteryStatsInfo/BatteryStatsInfo.msg.
//

#ifndef _BATTERYSTATSINFO_M_H_
#define _BATTERYSTATSINFO_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>BatteryStatsInfo/BatteryStatsInfo.msg</tt> by opp_msgc.
 * <pre>
 * message BatteryStatsInfo extends cMessage {
 * 	int source;
 *     int destination;
 *     double residualRelative;
 * }
 * </pre>
 */
class BatteryStatsInfo : public ::cMessage
{
  protected:
    int source_var;
    int destination_var;
    double residualRelative_var;

  private:
    void copy(const BatteryStatsInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BatteryStatsInfo&);

  public:
    BatteryStatsInfo(const char *name=NULL, int kind=0);
    BatteryStatsInfo(const BatteryStatsInfo& other);
    virtual ~BatteryStatsInfo();
    BatteryStatsInfo& operator=(const BatteryStatsInfo& other);
    virtual BatteryStatsInfo *dup() const {return new BatteryStatsInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual double getResidualRelative() const;
    virtual void setResidualRelative(double residualRelative);
};

inline void doPacking(cCommBuffer *b, BatteryStatsInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BatteryStatsInfo& obj) {obj.parsimUnpack(b);}


#endif // _BATTERYSTATSINFO_M_H_
